### ISSUE TITLE
Executing the bootstrapper project doesn't launch the main app

### ISSUE THREAD

**Issue by jjbrunton** [DrewKestell/BloogBot#1]
Hiya,

I'm trying to launch the project and I've managed to get it booting wow and completing the flow of the bootstrapper. I can see that die off but no application is launched.

I'm not asking you to support your demo but just curious as to where to start with troubleshooting no launch.

Really enjoyed reading through your blog by the way.

**Comment by DrewKestell** [comment]
I've seen that happen when there's a mismatch in the target architecture (x84 vs x64) between some of the projects. All the projects in source control should be targeting x86, so if you haven't changed anything, that's probably not the problem.

Troubleshooting ideas:

1) Make sure you're running Bootstrapper.exe (or have VisualStudio running) with elevated Administrator priviledges.

2) Make sure all the C++ projects have compiled. I forget, but something might be broken with the project dependencies where some C++ projects won't build if you just build the solution. Specifically, make sure Loader.dll exists in the build output directory.

3) I added some error checking in Bootstrapper -> Program.cs to make sure everything is working correctly, so I doubt this is the problem, but I have seen previously where Bootstrapper fails to write the Loader library into the WoW process [here](https://github.com/DrewKestell/BloogBot/blob/eb7ae557cfc97dfcb8110dbf447e489edc85e4a1/Bootstrapper/Program.cs#L69). So double check none of these Win32 API function calls are failing.

4) If you make it to the end of Bootstrapper -> Program.cs, it's safe to assume Loader.dll has successfully started execution inside the WoW process. See [this line](https://github.com/DrewKestell/BloogBot/blob/eb7ae557cfc97dfcb8110dbf447e489edc85e4a1/Loader/dllmain.cpp#L57) in Loader -> dllmain.cpp, we initialize a console window. So shortly after the console window for Boostrapper closes, you should see another one open. If that does happen, you should be able to debug by dumping some debug statements to the console from dllmain.cpp.

5) If you don't see a second console window open - well, I've seen that a few times before, but I've never been able to find the root cause. I suspect it's something related to windows security, or perhaps some missing .NET Framework dependency on your system.

**Comment by jjbrunton** [comment]
I think on the architecture point it's probably just that I'm attempting to run it against a recent version of WoW rather than the 2.4.3 you use. Presumably those versions are still running 32bit?

**Comment by DrewKestell** [comment]
Correct. I've only tested this code on 1.12.1 and 2.4.3.

**Comment by jjbrunton** [comment]
No worries! Great structure so I'll use it as inspiration in my tinkering :)

Thanks again.
