### ISSUE TITLE
Exception InvalidFunctionPointerInDelegate with turtle WoW

### ISSUE THREAD

**Issue by segatecm** [DrewKestell/BloogBot#21]
Hi Drew Kestell, I just try BloogBot in VS2022, Win10, turtle WoW 1.17.
But It report : Invalid function pointer 0x6e60f0 was passed to the runtime to be converted to a delegate. Passing an invalid function pointer for delegate conversion can cause crashes, corruption, or data loss.

Source Code:
static readonly CastAtPositionDelegate CastAtPositionFunction =
    Marshal.GetDelegateForFunctionPointer<CastAtPositionDelegate>(new IntPtr(MemoryAddresses.CastAtPositionFunPtr));

I think Turtle 1.17 is also based on WoW 1.12, so it should be fine to do it this way. But it failed. please help!

**Comment by DrewKestell** [comment]
Hey! Thanks for reporting this.

If I recall correctly, I never fully implemented the CastAtPosition function, because I ran into some challenges figuring out the function in the client (some issues with input or output parameters, or the calling convention, or something).

I'm not actively supporting this project right now, but if you want to try to fix this, I encourage you to submit a PR and link it to this issue. I'll review it and we can close it.

**Comment by segatecm** [comment]
I'm not fix it now. I did't know how to fix it, or the project can not work on turtle WOW?
I want to write a bot, can you give some adivce?

**Comment by DrewKestell** [comment]
I encourage you to join the discord and ask for help there: https://discord.gg/S4tvykaGcJ
