### ISSUE TITLE
cannot extract mmap from TBC 2.5.3 latest version

### ISSUE THREAD

**Issue by oiramario** [DrewKestell/BloogBot#3]
```
Fatal Error: failed to identify build version!


Supported build versions:

Vanilla: 5875, 6005, 6141
TBC:      8606
WOTLK:    12340
CATA:     15595
MOP:      18414
```

reference [https://github.com/DrewKestell/BloogBot/issues/2], however the sharing files are missing.
would you plz share them again? or teach me how to extract mmap from latest TBC classic myself?

Thanks for your great work!!!

**Comment by oiramario** [comment]
I've solve this issue, plz close it.

**Comment by DrewKestell** [comment]
Anyone else coming here and finding this, here are a few notes:

The original version of BloogBot used the ManGOS map extraction utilities. These were broken in that they ignored Liquid data from the origin WoW map data. This meant that regardless of how you called into the Detour API, the bots would not be smart enough to path around water.

This can be fixed by using the updated CManGOS map extraction utilities, found here: https://github.com/cmangos/mangos-tbc/tree/master/contrib/mmap](https://github.com/cmangos/mangos-tbc/tree/master/contrib)

Note that as the time of writing this, the documentation at that link is wrong.

They say the flag is `--debugOutput`, but if you look at the source code, the actual flag is `--debug`.
